#!/system/flashtool/sh

if [ -e /data/local/tmp/recovery ]
then
	export RECOVERYFILE=/data/local/tmp/recovery
else
	export RECOVERYFILE=/system/recovery/default
fi

if [ -e $RECOVERYFILE ]
then
	RES=$(cat $RECOVERYFILE|grep $1|cut -d "=" -f 2)
	if [ -z "$RES" ]
	then
		echo notfound
	else
		echo $RES
	fi
else
	echo notfound
fi